onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb80a/clk50
add wave -noupdate /tb80a/button
add wave -noupdate /tb80a/switch
add wave -noupdate -radix hexadecimal /tb80a/hex0
add wave -noupdate -radix hexadecimal /tb80a/hex1
add wave -noupdate -radix hexadecimal /tb80a/hex2
add wave -noupdate -radix hexadecimal /tb80a/hex3
add wave -noupdate -radix hexadecimal -childformat {{{/tb80a/led[9]} -radix hexadecimal} {{/tb80a/led[8]} -radix hexadecimal} {{/tb80a/led[7]} -radix hexadecimal} {{/tb80a/led[6]} -radix hexadecimal} {{/tb80a/led[5]} -radix hexadecimal} {{/tb80a/led[4]} -radix hexadecimal} {{/tb80a/led[3]} -radix hexadecimal} {{/tb80a/led[2]} -radix hexadecimal} {{/tb80a/led[1]} -radix hexadecimal} {{/tb80a/led[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/led[9]} {-height 15 -radix hexadecimal} {/tb80a/led[8]} {-height 15 -radix hexadecimal} {/tb80a/led[7]} {-height 15 -radix hexadecimal} {/tb80a/led[6]} {-height 15 -radix hexadecimal} {/tb80a/led[5]} {-height 15 -radix hexadecimal} {/tb80a/led[4]} {-height 15 -radix hexadecimal} {/tb80a/led[3]} {-height 15 -radix hexadecimal} {/tb80a/led[2]} {-height 15 -radix hexadecimal} {/tb80a/led[1]} {-height 15 -radix hexadecimal} {/tb80a/led[0]} {-height 15 -radix hexadecimal}} /tb80a/led
add wave -noupdate /tb80a/uart_txd
add wave -noupdate /tb80a/uart_rxd
add wave -noupdate /tb80a/uart_cts
add wave -noupdate /tb80a/uart_rts
add wave -noupdate /tb80a/de0_top/cpu/wb_rst_i
add wave -noupdate /tb80a/de0_top/cpu/reset
add wave -noupdate -expand -group clk_ena -radix octal /tb80a/de0_top/cpu/io_cnt
add wave -noupdate -expand -group clk_ena /tb80a/de0_top/cpu/ena
add wave -noupdate -expand -group clk_ena /tb80a/de0_top/cpu/io_ena
add wave -noupdate -expand -group clk_ena /tb80a/de0_top/cpu/io_rdy
add wave -noupdate /tb80a/de0_top/cpu/wb_clk_i
add wave -noupdate -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/wb_adr_o[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_adr_o[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/wb_adr_o[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_adr_o[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/wb_adr_o
add wave -noupdate -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/wb_dat_i[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_i[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_i[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_i[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_i[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_i[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_i[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_i[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/wb_dat_i[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_i[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_i[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_i[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_i[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_i[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_i[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_i[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/wb_dat_i
add wave -noupdate -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/wb_dat_o[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_o[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_o[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_o[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_o[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_o[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_o[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/wb_dat_o[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/wb_dat_o[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_o[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_o[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_o[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_o[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_o[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_o[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/wb_dat_o[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/wb_dat_o
add wave -noupdate /tb80a/de0_top/cpu/wb_cyc_o
add wave -noupdate /tb80a/de0_top/cpu/wb_stb_o
add wave -noupdate /tb80a/de0_top/cpu/wb_ack_i
add wave -noupdate /tb80a/de0_top/cpu/wb_we_o
add wave -noupdate /tb80a/de0_top/cpu/io_rdy
add wave -noupdate /tb80a/de0_top/cpu/wb_tgc_o
add wave -noupdate -expand -group Tx /tb80a/de0_top/cpu/t1
add wave -noupdate -expand -group Tx /tb80a/de0_top/cpu/t2
add wave -noupdate -expand -group Tx /tb80a/de0_top/cpu/t3
add wave -noupdate -expand -group Tx /tb80a/de0_top/cpu/t4
add wave -noupdate -expand -group Tx /tb80a/de0_top/cpu/t5
add wave -noupdate -expand -group Mx /tb80a/de0_top/cpu/m1
add wave -noupdate -expand -group Mx /tb80a/de0_top/cpu/m2
add wave -noupdate -expand -group Mx /tb80a/de0_top/cpu/m3
add wave -noupdate -expand -group Mx /tb80a/de0_top/cpu/m4
add wave -noupdate -expand -group Mx /tb80a/de0_top/cpu/m5
add wave -noupdate -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/i[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/i[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/i[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/i[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/i[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/i[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/i[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/i[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/i[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/i[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/i[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/i[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/i[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/i[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/i[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/i[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/i
add wave -noupdate -radix hexadecimal /tb80a/de0_top/cpu/r
add wave -noupdate -radix hexadecimal /tb80a/de0_top/cpu/xr
add wave -noupdate -expand -group rmux -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/a[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/a[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/a[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/a[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/a
add wave -noupdate -expand -group rmux -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/mxi[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxi[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/mxi[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxi[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/mxi
add wave -noupdate -expand -group rmux -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/mxo[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/mxo[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/mxo[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/mxo[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/mxo
add wave -noupdate -expand -group rmux -group mxrN /tb80a/de0_top/cpu/mxr0
add wave -noupdate -expand -group rmux -group mxrN /tb80a/de0_top/cpu/mxr1
add wave -noupdate -expand -group rmux -group mxrN /tb80a/de0_top/cpu/mxr2
add wave -noupdate -expand -group rmux -group mxrN /tb80a/de0_top/cpu/mxr3
add wave -noupdate -expand -group rmux -group mxrN /tb80a/de0_top/cpu/mxr4
add wave -noupdate -expand -group rmux -group mxrN /tb80a/de0_top/cpu/mxr5
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/mxrh
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/mxrl
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/mxw16
add wave -noupdate -expand -group rmux -color Cyan /tb80a/de0_top/cpu/mxwadr
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/mxwh
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/mxwl
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/iad16
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/inc16
add wave -noupdate -expand -group rmux /tb80a/de0_top/cpu/dec16
add wave -noupdate -expand -group rmux -radix hexadecimal /tb80a/de0_top/cpu/r16_bc
add wave -noupdate -expand -group rmux -radix hexadecimal /tb80a/de0_top/cpu/r16_de
add wave -noupdate -expand -group rmux -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/r16_hl[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_hl[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/r16_hl[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_hl[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/r16_hl
add wave -noupdate -expand -group rmux -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/r16_pc[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_pc[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/r16_pc[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_pc[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/r16_pc
add wave -noupdate -expand -group rmux -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/r16_sp[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_sp[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/r16_sp[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_sp[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/r16_sp
add wave -noupdate -expand -group rmux -radix hexadecimal -childformat {{{/tb80a/de0_top/cpu/r16_wz[15]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[14]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[13]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[12]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[11]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[10]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[9]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[8]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[7]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[6]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[5]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[4]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[3]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[2]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[1]} -radix hexadecimal} {{/tb80a/de0_top/cpu/r16_wz[0]} -radix hexadecimal}} -subitemconfig {{/tb80a/de0_top/cpu/r16_wz[15]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[14]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[13]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[12]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[11]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[10]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[9]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[8]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[7]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[6]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[5]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[4]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[3]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[2]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[1]} {-height 15 -radix hexadecimal} {/tb80a/de0_top/cpu/r16_wz[0]} {-height 15 -radix hexadecimal}} /tb80a/de0_top/cpu/r16_wz
add wave -noupdate /tb80a/de0_top/cpu/xchg_dh
add wave -noupdate /tb80a/de0_top/cpu/xchg_tt
add wave -noupdate /tb80a/de0_top/cpu/vm_cena
add wave -noupdate /tb80a/de0_top/cpu/ms0
add wave -noupdate /tb80a/de0_top/cpu/ms1
add wave -noupdate /tb80a/de0_top/timer/ena_f2
add wave -noupdate /tb80a/de0_top/timer/ena_ms
add wave -noupdate /tb80a/de0_top/timer/ena_us
add wave -noupdate /tb80a/de0_top/timer/irq_50
add wave -noupdate /tb80a/de0_top/timer/rst
add wave -noupdate /tb80a/de0_top/cpu/id_hlt
add wave -noupdate /tb80a/de0_top/cpu/inta
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3301711 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {3016322 ps} {3823678 ps}
